apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bthode/microk8s-argocd.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
