apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: ~1.17.2
    helm:
      values: |
        fake: bar
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system
