apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: ~1.17.2
    helm:
      values: |
        fake: bar
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
