apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
spec:
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.2
    chart: istiod
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
