apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      values: |
        "fullnameOverride: sealed-secrets-controller"
    chart: sealed-secrets
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: ~2.9.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
